spring:
  application:
    name: spring-batch-example
  sql:
    init:
      mode: always
      schema-locations: classpath:profile.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    job:
      names: ${job.name:NONE}
      enabled: true

server:
  port: 8080